name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Preview URL: ⏳ deployment is in progress..."

      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - run: pnpm run build

      - id: deploy
        name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: ${{ github.event_name == 'push' && 'deploy' || 'versions upload' }}

      - if: ${{ github.event_name == 'pull_request' }}
        name: Post preview URL comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Preview URL: ${{ steps.deploy.outputs.deployment-url }}"
